# docker-compose.yml

version: '3.8'
services:

  # Docker connection string: postgres://postgres:password@localhost:5432/

  postgres:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres:
